### ISSUE TITLE
hydra makeAPIRequest, queryparameters

### ISSUE THREAD

**Issue by drosi94** [flywheelsports/hydra#75] opened 2017-03-31 11:00 UTC
Hello, i would to send an api request to one microservice using query params

  hydra.makeAPIRequest(hydra.createUMFMessage({
    to: 'users-service:[get]/api/users' + '?email=' + email + '&password=' + password,
    from: 'authentication-service:/',
    body: {}
  }))
I got this error to response: 

![capture](https://cloud.githubusercontent.com/assets/3253526/24547810/634d8240-161a-11e7-9e6c-8a09ecc766bf.PNG)

**Comment by cjus** [comment] 2017-04-01 14:09
@drosi94 I'll look into this - thanks for reporting!

**Comment by cjus** [comment] 2017-04-02 04:55
@drosi94 A quick update. The issue is that makeAPIRequest doesn't properly handle query params. Under the hood, makeAPIRequest using the [node request module](https://www.npmjs.com/package/request). Looks like it might be necessary to use node's querystring module to parse the query string and properly send it to the request modules option param. I'll test this and create a patch this weekend.

**Comment by cjus** [comment] 2017-04-02 17:54
@drosi94 can you post a code snippet for your user-service /api/users route handler?

**Comment by cjus** [comment] 2017-04-02 17:59
When using query strings with express you need to use `response.query.email` and `response.query.password` to get at the values. Unless you define your routes this way: `/api/users/:email/:password`.  See: http://junerockwell.com/difference-parameters-query-strings-express-js/

**Comment by cjus** [comment] 2017-04-06 15:38
@drosi94 closing this issue.

**Closed by cjus** 2017-04-06 15:38 UTC

**Comment by drosi94** [comment] 2017-04-06 19:07
Thank you very much!
